### ISSUE TITLE
Fig. 4.9 heading indent mistake

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#1]
[raised by Cedric Simon, 2016-03-18]

I stumbled across the following document https://www.w3.org/TR/jlreq/#processing_of_runin_heading and spotted a tiny mistake (I think).

The fig. 4.9 describes the third heading being indented by "9pt x 6" instead of "9pt x 8" as explained in the note (1) above:

"[...] For example, when the character size of main text is 9 point, the indent of a large heading is 9 point by 4 times, medium-heading is 9 point by 6 times, small-heading is 9 point by 8 times."

**Comment by himorin** [comment]
figure 4.9: Figure 193 [img3_1_9.png](https://w3c.github.io/jlreq/#fig3_1_9)

**Comment by himorin** [comment]
Toshi Kobayashi san will fix English version of image. No need to edit Japanese version (which is correct).

**Comment by himorin** [comment]
Closing this, PR merged: agreed to merge on last F2F, and checked.
