### ISSUE TITLE
Add table borders to ones in Appendix A

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#101]
from item 4. in https://github.com/w3c/jlreq/pull/99#issuecomment-508756776
There are several tables in [Appendix A](https://w3c.github.io/jlreq/#appendix_1) for classes of characters, we had border in [2nd ed.](https://www.w3.org/TR/jlreq/#character_classes) but not for now.

**Comment by himorin** [comment]
better to share css definitions with termlist to charclass, will open PR after PR #99 merged.

**Comment by kidayasuo** [comment]
@r12a This reminds me of need for a pre-release testing. Is there a standard process, or how is it usually done?

**Comment by himorin** [comment]
closing per #132 merged.
@kidayasuo shall I file new issue for pre-release testing, or continue email conversation?

**Comment by kidayasuo** [comment]
Yes, please file a new issue. As this revision got structural changes in addition to relatively simple errata fixes, I believe we need more testing.
What are standard practices? also I wonder how it was done on the first version.
