### ISSUE TITLE
[gap-analysis] update sections to current typography index one

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#110]
section index is now inconsistent between https://w3c.github.io/typography/ and JLreq one. if need, update current jlreq version to match with the master (typography).
(is required?)

**Comment by r12a** [comment]
Not a good idea.  The reason we say that the top levels of the gap-analysis doc shouldn't be changed is because they are harmonised with scripts and data related to the language matrix and other gap-analyses.  They do not have to be 100% aligned with the typography index.

**Comment by himorin** [comment]
Thank you for reminding me on that point. Yes, I shall refer checklist at https://w3c.github.io/typography/gap-analysis/, but not typography index...
Let me close this.
