### ISSUE TITLE
[gap-analysis] Add text on start/end of line

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#113]
Add discussion results from [Aug 8 F2F](https://lists.w3.org/Archives/Public/public-jlreq-admin/2019JulSep/0031.html) for start/end of line, on JLReq sections 3.1.7, 3.1.8, to [4.1 line breaking](https://w3c.github.io/jlreq/gap-analysis/#linebreak).

**Comment by himorin** [comment]
As in https://github.com/w3c/jlreq/pull/114/files, implemented in CSS specs.
Relevant wpt tests are in `css/css-text/line-break`, as:

- tests for all `line-break-loose-`, `line-break-normal-`, `line-break-strict-`
- 011.xht: CJ (small kana)
- 012.xht: U+30FC, U+FF70
- 013.xht: U+301C, U+30A0
- 014.xht: U+3005, U+303B, U+309D, U+309E, U+30FD, U+30FE
- 015(ab).xht: U+2025, U+2026
- 016a.xht: U+30FB, U+FF1A, U+FF1B, U+FF65
- 016b.xht: U+203C, U+2047, U+2048, U+2049, U+FF01, U+FF1F
- 017a.xht: U+00B0, U+2030, U+2032, U+2033
- 017b.xht: U+2103, U+FF05, U+FFE0
- 018.xht: U+20AC, U+2116, U+FF04, U+FFE1, U+FFE5
- hyphens-00X.html: U+2010, U+2013

some tests fails [in test result](https://wpt.fyi/results/css/css-text/line-break?label=experimental&label=master&aligned), esp safari for loose. Do we want to have a gap issue to record this? @kidayasuo

**Comment by kidayasuo** [comment]
Yes, let's record the failure cases in a gap issue.

**Comment by r12a** [comment]
@himorin could you also look at the i18n test suite to see which of these are covered and which not?

**Comment by himorin** [comment]
> @himorin could you also look at the i18n test suite to see which of these are covered and which not?

Yes, I'm pinging on test development also in parallel to this, and hope to have some clear next step(s) shortly.

**Comment by himorin** [comment]
as: https://github.com/w3c/jlreq/issues/274

**Comment by himorin** [comment]
sorry forgot to close this after filing gap issue...
