### ISSUE TITLE
Cannot switch language to Japanese

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#123]
Not sure if I should report it to ReSpec or here, so reporting here first.

In the current ED, switching lanauge to 日本語 doesn't work, because script.js ([L63 and L65](https://github.com/w3c/jlreq/blob/6c08870aee0d7dc1ae7ff2471377c59f5af6cff2/script.js#L63-L65)) emits two uncaught `TypeError`s, caused by these two lines in the `switchLang` function:

```javascript
document.getElementById('editor').textContent = translations[lang].editors
document.getElementById('formerEditors').textContent = translations[lang].formerEditors
```

I might be missing something, but it looks like the document doesn't have an element with ID `editor` or `formerEditors`.

/cc @r12a

**Comment by r12a** [comment]
Strange.  It used to work. @himorin can you find any PR that may have changed things?

**Comment by aphillips** [comment]
Did you change to 日本語 or `ja`?

**Comment by r12a** [comment]
There's a button at the top right with the label 日本語 which should remove the English text, but now doesn't.

**Comment by r12a** [comment]
Should be fixed by https://github.com/w3c/jlreq/commit/75d6f82b8f97dce9b651b3471c24628bdd07e21c

Please reopen if not.  Note that i did a direct commit, so it will be necessary to synch local files before doing another PR.
