### ISSUE TITLE
Need to create labels for sub projects such as gap-analysis and simple-ruby

### ISSUE THREAD

**Issue by kidayasuo** [w3c/jlreq#135]

**Comment by r12a** [comment]
@kidayasuo I can create labels for you. Let me know what labels you want, with a short description wrt usage.

**Comment by kidayasuo** [comment]
For now we need gap-analysis and simple-ruby. @shimono?

**Comment by xfq** [comment]
cc @himorin

**Comment by r12a** [comment]
@kidayasuo i was particularly interested in the short description of how you expect the labels to be used. I'll add a description when i create the labels.

**Comment by himorin** [comment]
how about simply:

- **gap-analysis**: issues and discussions on Japanese Gap Analysis document
- **simple-ruby**: issues and discussions on Rules for Simple Placement of Ruby

**Comment by r12a** [comment]
That sounds fine to me. @kidayasuo ?

**Comment by kidayasuo** [comment]
fine with me.

**Comment by r12a** [comment]
done

**Comment by kidayasuo** [comment]
thank you!
