### ISSUE TITLE
Create translation for respec front matter boilerplate

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#136]
The section "Status of This Document" has some text in English at the bottom which is supplied by respec automatically, and can be seen in the rendered document.  It starts with "This document was published by...." and ends at the bottom of the section with a link to the Process Doc.

I suggest that we translate this as a single block of paragraphs and insert them all before the location where the boilerplate will appear.  You can see how we did this for the Chinese lreq doc at http://w3c.github.io/clreq/, and i think we should follow the same model.

**Comment by himorin** [comment]
will this help something on this (for future update opportunity??)?
https://github.com/w3c/respec/issues/113

**Comment by himorin** [comment]
merged.
