### ISSUE TITLE
Update source files for images of jlreq

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#140]
This is not an issue for JLReq note itself, but just housekeeping tracker for source files in images/source/ directories.

- [ ] check files changed/updated
- [ ] sync and update files in git-lfs

**Comment by himorin** [comment]
Last batch on image source files was in https://github.com/w3c/jlreq/commit/75c8861e71f1be8e065ea508e5b935b642dbe4e3, which was performed over source files at the point of 2019 May.
Update from that point is https://github.com/w3c/jlreq/pull/121, and I will ask source files for two.

**Comment by kidayasuo** [comment]
Removing milestone as it does not block the release. This has to be done nonetheless.
