### ISSUE TITLE
Pre-release tasks for JLReq errata update

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#141]
from #101, comment by @kidayasuo 

> Yes, please file a new issue. As this revision got structural changes in addition to relatively simple errata fixes, I believe we need more testing.
> What are standard practices? also I wonder how it was done on the first version.

We need to develop list of required checks to be performed, and go through these checks.

**Comment by kidayasuo** [comment]
Do you know if there are standard process of testing in w3c?  if there is no such thing probably we (TFReq TF members) each would take a look by comparing pre- and post- update side by side.

**Comment by himorin** [comment]
Usually [htmldiff](https://services.w3.org/htmldiff) is used for comparison, but I don't think it will work for this our case...

**Comment by kidayasuo** [comment]
I agree. what we need to test is visual and probably comparing the source is not very effective for that purpose.

**Comment by r12a** [comment]
There are, of course, other tests we run before creating a WD in the w3.org/TR space, which include:
- check for valid HTML
- check for valid CSS
- check all links work
- check conformance with pubrules

Hopefully, people editing the ED always ensure that the result of their commits is valid HTML and that the links work.

However, there is no existing procedure that i'm aware of for checking visual appearance of the document other than due diligence by the editor.

**Comment by kidayasuo** [comment]
Thank you Richard.
@himorin Were the four tests Richard mentioned run on the update?

**Comment by himorin** [comment]
For side-by-side test, I wandered there is any easy way to check word-by-word comparison, with using several text tools like grep/sed/diff, but almost giving up to build a set of way: such that we switched to use respec that introduces automatic generation of links (but not using a element in document) and it changes text within a line.
I'll try to check side-by-side overview comparison and also in composed format again (like recently found mixed lines in terminology section).

For generic(?) tests, I did tests with locally generated ready-to-go document set at https://jlreq-old.ksw.himor.in/2019-jlreq/

- [HTML validator](https://validator.w3.org/nu/): no error/warning except for bdi and composing character
- [CSS validator](https://jigsaw.w3.org/css-validator/): valid
- [pubrules](https://www.w3.org/pubrules/?url=https%3A%2F%2Fjlreq-old.ksw.himor.in%2F2019-jlreq%2F&profile=FPWG-NOTE&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004) note two errors (except html validator above) and two warnings
  - (error) title and h1 mismatch: what to do for this kind of composed format?
  - (error) patent policy paragraph not found: but it actually exists,,,
  - (warning) wrapping section number by class="secno"
  - (warning) add back-to-top hyperlink at the end
- link checker found no error

**Comment by kidayasuo** [comment]
Thank you for running all the tests.

As for the pub rules errors, what is the nature of the "title and h1 mismatch" error? I guess the patent policy error can be ignored as we actually have one. Do you think we can safely ignore the warnings?

As for visual check, how about we jlreq member share the responsibility and each take a portion of the document?  The focus will be on the formatting, such as charts, indentation, position of graphics x etc. and will be done on English only and Japanese only pages. What do you think?

**Comment by himorin** [comment]
I've (roughly) gone through 'all' mode for checking inconsistency or divided sentences like one in https://github.com/w3c/jlreq/pull/139, and found followings:

- last sentence of first note in 4.2.5 b. (https://w3c.github.io/jlreq/#n237) lack Japanese text
- text for figure 330 (https://w3c.github.io/jlreq/#en-app6_5) lacks its-locale-filter-list
- it seems some description in terminology is wrapped by div but not p (like https://w3c.github.io/jlreq/#term.gutter), better to add div to margin definition for p in css?

**Comment by himorin** [comment]
> As for the pub rules errors, what is the nature of the "title and h1 mismatch" error? I guess the patent policy error can be ignored as we actually have one. Do you think we can safely ignore the warnings?

I found adding one U+20 could remove warning. Let me push PR shortly.

> As for visual check, how about we jlreq member share the responsibility and each take a portion of the document? The focus will be on the formatting, such as charts, indentation, position of graphics x etc. and will be done on English only and Japanese only pages. What do you think?

That could be an option, or I may take some part (or to-where-I-can-finish) and proceed from now before next F2F?

**Comment by kidayasuo** [comment]
> That could be an option, or I may take some part (or to-where-I-can-finish) and proceed from now before next F2F?

sure. that is great. thank you so much.

**Comment by xfq** [comment]
> (error) patent policy paragraph not found: but it actually exists,,,

I think the document in https://jlreq-old.ksw.himor.in/2019-jlreq/ lacks the "W3C maintains a public list of any patent disclosures..." text, as you can see in the Status of This Document of [clreq](https://www.w3.org/TR/clreq/). I'm not sure why, though, since we do have the `wgPatentURI` option in jlreq's `respecConfig`.

**Comment by kidayasuo** [comment]
Is #149 the only remaining open issue?

**Comment by himorin** [comment]
> Is #149 the only remaining open issue?

I assume 'yes'.

**Comment by himorin** [comment]
for now, following one error is reported (with local update on specStatus, previousPublishDate, previousMaturity) from pubrules, html, css, link: 

- two id="w3c_process_revision", this is from adding Japanese text for SoTD, and I'd propose to remove id in Japanese version.

**Comment by kidayasuo** [comment]
do we know how to solve it?

**Comment by himorin** [comment]
per discussion with @kidayasuo , pushed PR #216 for this
>     * two id="w3c_process_revision", this is from adding Japanese text for SoTD, and I'd propose to remove id in Japanese version.

**Comment by himorin** [comment]
will re-check and close this shortly.

**Comment by kidayasuo** [comment]
Are there any remaining tasks? Let’s finish this up. #140 is a maintenance work and does not block the release.

**Comment by himorin** [comment]
Checked pubrules,css,html,link on current HEAD with following change, found two link errors:
(test files at: https://storage.himor.in/jlreq-20200716/Overview.html )

```
         specStatus: "WD",
         previousPublishDate:  "2012-04-03",
         previousMaturity:  "WG-NOTE",
```

Link errors were link to 'index.html?lang=xx'. I'll push PR to fix.

**Comment by himorin** [comment]
closing this, new NOTE had been published.
