### ISSUE TITLE
space between head and page number

### ISSUE THREAD

**Issue by okumuralab** [w3c/jlreq#18]
It looks like 2.6.1 c "when arranging running heads and page numbers together on the same horizontal line, the space between the running head and the page number should be double or one and a half times the character size of the running head" contradicts Fig. 2.48(f) and Fig. 2.49(b), where the heads are centered.  The "double or one and a half" rule should apply only when both the head and the page number are similarly aligned (e.g. both are left-aligned on the left page).

**Comment by himorin** [comment]
- Figure 2.48: Figure 48 [img1_28.png](https://w3c.github.io/jlreq/#fig1_28)
- Figure 2.49: Figure 49 [img1_29.png](https://w3c.github.io/jlreq/#fig1_29)

**Comment by himorin** [comment]
Toshi Kobayashi san confirmed no need to fix figures, but added text of example for clarification into section 2.6.1 (c)

**Comment by himorin** [comment]
closing, PR merged.

**Comment by himorin** [comment]
sorry, I did wrong operation. closing this properly...
