### ISSUE TITLE
inconsistent sentence in 3.7.3.b.1

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#188]
link: https://w3c.github.io/jlreq/#id275

Ja/En text is inconsistent (not by means of its context/description)

**Comment by xfq** [comment]
This is the current English and Japanese text:

> Positions where line breaks are prohibited: between contiguous European numerals; between two EM DASH "—" characters; between two TWO DOT LEADER "‥" characters; between two HORIZONTAL ELLIPSIS "…" characters; and so on. These sequences should be treated as a single block.

> 2行に分割してはならない箇所．連数字中の文字（cl-24）の字間，欧文用文字（cl-27）の字間，同一の分離禁止文字（cl-08）の字間など．これらの文字列は一体として扱いたいからである．

European numerals are in cl-24. EM DASH, TWO DOT LEADER, and HORIZONTAL ELLIPSIS are in cl-08. There is no mention of cl-27 in the English text. If the Japanese is correct, maybe we can change the English text to something like this:

> Positions where line breaks are prohibited: between grouped numerals (cl-24); between Western characters (cl-27); between two inseparable characters (cl-08); and so on. These sequences should be treated as a single block.

**Comment by kidayasuo** [comment]
I agree with the change Richard suggested.
