### ISSUE TITLE
jlreq pages links actually go to alreq

### ISSUE THREAD

**Issue by srl295** [w3c/jlreq#19]
https://github.com/w3c/jlreq/blob/gh-pages/gap-analysis/index.html or https://w3c.github.io/jlreq/gap-analysis/ have links to the `alreq` instead of `jlreq` project.

**Comment by xfq** [comment]
Thank you!

Fixed in bb6353e24cf53756e1cc7c4e385fdaef2c4251c8.

**Comment by r12a** [comment]
Thanks, @srl295 and @xfq !
