### ISSUE TITLE
Inconsistent paragraph in 3.7.4

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#190]
https://w3c.github.io/jlreq/#h-note-152

Ja/En text is inconsistent here. For example, 水平の罫線を使用した分数 (fractions with horizontal lines) is not mentioned in the English text.

**Comment by himorin** [comment]
two point need to be fixed, it seems
- list of examples of math symbols (@kidayasuo what list do you think appropriated here?; pointed item - `水平の罫線を使用した分数` is missing from English version, `GREEK CAPITAL LETTER SIGMA "Σ"` is used in English text for `総和記号` (Summation) but should be replaced by `SUMMATION "Σ"` or something?)
- `mathematical and scientific notations like numerical formulae are out of scope` seems not in Japanese text

**Comment by kidayasuo** [comment]
I guess the sentence that were added to the English translation “Also, mathematical and scientific notations like numerical formulae are out of scope for this document.” is a translation of “水平の罫線を使用した分数”. It is actually a better description of what is out of scope. I would leave this as-is, or improve the Japanese.

**Comment by himorin** [comment]
Ah, I see. I thought some simple one from Japanese text like [one in Ichitaro](https://support.justsystems.com/faq/1032/app/servlet/qadoc?QID=039143), and complex mathematical formulae like in paper from English text...

How about:

- `mathematical and scientific notations used for numerical formulae`
- `やぐら組 (水平の罫線を使用した分数など) に利用される罫線要素，根号式，積分記号，総和記号` or,,?

**Comment by kidayasuo** [comment]
do we need to change anything here, especially the english?

**Comment by himorin** [comment]
> do we need to change anything here, especially the english?

actually, I think no. Just in case, considering this raised issue, there might be a room to modify text slightly.

**Comment by kidayasuo** [comment]
I think we can close this, or alternatively, we could keep this to improve the original Japanese. In either case I do not think this is for the milestone 1.

**Comment by kidayasuo** [comment]
I would be closing this.
