### ISSUE TITLE
[simple-ruby] Editorial nits

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#191]
The following are requests for simple editorial nits throughout the document, gathered in one place.  I will raise separate issues for items that may need more discussion.

Status of This Document
https://w3c.github.io/jlreq/docs/simple-ruby/#sotd

non-japanese -> non-Japanese

Internationalizatoin Interest Group -> Internationalization Interest Group

3.2 Placement of mono-ruby 
https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-mono-ruby

NOTE
some amout -> some amount

but recognize the -> but recognizes the 

BP #5 
at the end of then line -> at the end of the line

3.3 Placement of group-ruby
https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-group-ruby

under fig 10
capped at than half -> capped at no more than half

fig 13
i think it would be clearer if the 'package' example and the 'frontier' example were separated by a small amount of vertical space.

BP #3 
see Figure 14 -> see Figure 13 (?)

BP #5
where it is wrapped, and is then processed -> where it is wrapped, it is then processed

3.4 Placement of Jukugo-ruby
https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-jukugo-ruby

BP #3
has be described -> has been described

**Comment by r12a** [comment]
Um. It looks like i already fixed these things in https://github.com/w3c/jlreq/commit/2c5316c05e496c2ff11555602d7d997ef9d15c0d#diff-ba06f5a5d0f25a310b91ee537735740e

Perhaps someone could just check them for me, since i seem to be losing my marbles...

**Comment by r12a** [comment]
@xfq made a couple more fixes. See https://github.com/w3c/jlreq/commits/gh-pages/docs/simple-ruby/index.html

**Comment by xfq** [comment]
I confirm that these have been fixed.

**Comment by xfq** [comment]
Except one, perhaps: the amount of vertical space between 'package' and 'frontier' in [Figure 13](https://w3c.github.io/jlreq/docs/simple-ruby/#ruby-west)

**Comment by r12a** [comment]
Thanks @xfq .

**Comment by frivoal** [comment]
@r12a I am not sure what you mean with:
> would be clearer if the 'package' example and the 'frontier' example were separated by a small amount of vertical space.

Do you want a small amount of additional space, or a smaller amount of space than is currently used?

**Comment by r12a** [comment]
Hmm. On reflection, i think we can leave as is.  Sorry for the noise.

**Comment by xfq** [comment]
Can we close this issue now?
