### ISSUE TITLE
[simple-ruby] Normativeness

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#192]
If we publish this as a WG Note there is no normativity, so i think we should remove all text that says "_This section is non-normative._" or similar.

And also remove the 2 subsection headings in the References section.

**Comment by xfq** [comment]
Looks like a duplicate of https://github.com/w3c/jlreq/issues/25

**Comment by r12a** [comment]
Closing in favour of w3c/simple-ruby#2 .  Thanks @xfq .
