### ISSUE TITLE
Fig. 3.83 doesn't match its description

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#2]
From: Kobayashi Toshi binn@k.email.ne.jp
Date: Fri, Jan 30, 2015 at 10:08 AM

Xidorn Quan さん wrote

> The text before Fig. 3.83 says:
> 
> > There is another variation that allows ruby text to overhang any
> > ideographic characters (cl-19), hiragana (cl-15) or katakana (cl-16) up to
> > the full-width size of a ruby character (see Fig. 3.83)
> 
> However, in the figure, the ruby text only overhang up to half-width size
> of a ruby character, even if the description says it can overhang more.
> (See the "懐(ふところ)" in the figure)
> 
> I guess either the figure or the description should be changed.

The change of "Fig. 3.83" is unnecessary.

"full-width" of "note 3" is a mistake. "full-width" of "note 3" is "h
alf em".

**Comment by himorin** [comment]
Figure 3.83: Figure 139 [img2_3_32.png](https://w3c.github.io/jlreq/#fig2_3_32)

**Comment by himorin** [comment]
Toshi Kobayashi san agreed that figures (en/ja) are correct and need to fix the text of note.

**Comment by himorin** [comment]
Closing this, PR merged: agreed to merge on last F2F, and checked.
