### ISSUE TITLE
[simple-ruby] Leave room for manual overrides

### ISSUE THREAD

**Issue by bert-github** [w3c/jlreq#200]
The rules aim to give a reasonable placement in all cases, but, as the introduction mentions, people have used other placements to solve specific problems. One would hope that a system that implements the simple placement rules still allows a typographer to do things differently. Maybe the text should say that somewhere. It currently only says that explicitly for the font size of the ruby, which need not be 1/2.

**Comment by frivoal** [comment]
If this were a normative specification, it would be important to be clear about what is a should and what is a must, and where the extension points are.

However, it is not that kind of document, and I think it is better to focus on simply describing the method as it is. In any real system, there will be much more complication brought by interaction with other features (or other languages), as well as a desire for further nobs and levers to tweak things, but that's out of scope here, and would complicate the body of the text.

However, if this is just about adding a sentence to the introduction, without complicating the main text, then why not. For instance, we could add towards the end of [1.2](https://w3c.github.io/jlreq/docs/simple-ruby/#web-ruby-placement)

> The following is a proposal for a simple processing system. The target audience is implementers and specification writers. **It is expected that a full system may be more complex that what is described here, both due to the interaction with other features or other writing systems, and because those designing such system may wish to provide additional options.**

**Comment by r12a** [comment]
Iiuc, during the i18n telecon, Bert was also concerned that authors should be able to not follow these rules in certain circumstances, eg. to do katatsuki for certain ruby items rather than nakatsuki.  Maybe that would be covered by changing 'additional' in the last sentence above to 'alternative'?
