### ISSUE TITLE
add simple-ruby repository in link (or somewhere)

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#208]
We may need a link to a new simple-ruby repository in the link section (or somewhere else like new section for a list of documents?)

(as reminder/todo to myself and jlreq TF...)

**Comment by r12a** [comment]
Indeed. I've still yet to tidy up in the jlreq repo.  When i do that i'll add a link to the jlreq GH homepage.

**Comment by r12a** [comment]
Added a link to https://github.com/w3c/jlreq/blob/gh-pages/README.md
