### ISSUE TITLE
Figure 30 が日本語と English で少し図が違う

### ISSUE THREAD

**Issue by foomin10** [w3c/jlreq#253]
Section 2.3.2 の列記 d 号の列記 2 号にある図 Figure 30: “How to process incomplete number of lines on a multi-column format page (horizontally set book).”「横組の段組における改丁・改ページの直前ページの処理例」において日本語と English で少しだけ意図してないであろう差異があります。

- [Figure 30 (en) (w3c/jlreq/blob/gh-pages/images/img1_25.png)](https://github.com/w3c/jlreq/blob/gh-pages/images/img1_25.png)
- [Figure 30 (ja) (w3c/jlreq/blob/gh-pages/images_ja/img1_25.png)](https://github.com/w3c/jlreq/blob/gh-pages/images_ja/img1_25.png)

English の方の矢印の右側に灰色がひとつ欠けています。

たぶん間違いだと思いますので、報告いたしました。

**Comment by himorin** [comment]
Thank you for your good eye @foomin10 , we've updated the image (will appear to editors' draft shortly).
