### ISSUE TITLE
English translation problem

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#261]
https://w3c.github.io/jlreq/#n211

> Books usually begin with page one.
> 書籍は，表（おもて）面を1ページとして開始する．

There is a problem with the English translation of this sentence. Maybe it means that a book starts with the recto side?

**Comment by xfq** [comment]
Just FYI - the clreq TF also has related discussions: https://github.com/w3c/clreq/issues/354

**Comment by himorin** [comment]
PR raised.
- It seems following Japanese text has an error also.
- for recto and page 1, preceding item states `Always begin with odd pages, i.e. new recto.` and could be written as is, but added in PR to sync between en/ja.
- fixed a position of reference to a figure in English ver (figure shows only vertical writing mode, but not horizontal one)
- last sentence `begin with a right page after a new recto` should be `begin with a right page at a new recto`? (or no need to have the last part - `a new recto`)
