### ISSUE TITLE
[simple-ruby] 1-1-3 annotations in jukugo ruby

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#27]
3.4 Placement of Jukugo-ruby (bullet 2)
https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-jukugo-ruby-0

> If even a single ruby string is longer than its corresponding base character when laid out without inter-letter spacing, the processing is identical to group-ruby (see Figure 17 and Figure 18). 

What about when you have 3 base kanji with hiragana annotations of 1, 1, and 3 characters, respectively?  In jlreq is shows a gap between the first hiragana character and the others. Are we countermanding that here, or omitting to mention it?

A third example would be useful, because this is one of the key cases that distinguished jukugo-ruby in previous discussions.

**Comment by macnmm** [comment]
Agreed more illustrations would be helpful. Jukugo ruby allows overhang to adjacent base glyphs (pushing their ruby if needed), and allows line breaking between base glyphs, but otherwise the normal ruby spacing rules apply with gaps between them when they are shorter than the width of base glyphs they annotate.

**Comment by frivoal** [comment]
> Are we countermanding that here, or omitting to mention it?

My understanding is that we're countermanding it. Yes, richer models exist, but for a "simple model", this does the job.

**Comment by r12a** [comment]
Ouch. Seems to me that that makes the overall handling of ruby (for those who want to do more than simple stuff) much more difficult to implement and describe.  I also think it will produce what some see as incorrect results, and some degree of confusion on top of the confusion that already exists around jukugo-ruby.  If we want to propose simple solutions for authors that don't do what jukugo-ruby normally does, perhaps we should simply say: if this is the case, then use group ruby instead.

**Comment by r12a** [comment]
How about something like this:

> For simple ruby implementations, if even a single ruby string is longer than its corresponding base character when laid out without inter-letter spacing the resulting layout would look identical to group-ruby.

And perhaps in bullet 3 also change 'processing' to 'resulting layout'.

**Comment by r12a** [comment]
If it doesn't take too much time, it would be nice to show an example that has the 1-1-3 arrangment too.
