### ISSUE TITLE
GitHub issue 練習用スペース（GitHub issue playground）

### ISSUE THREAD

**Issue by kidayasuo** [w3c/jlreq#273]
ここは JLReq TF メンバーが GitHub issue の使い方を練習する場所です。自由に書き込みどうぞ。
This is a place to practice using GitHub for JLReq TF contributors.

もし書き込み方がわからない場合は public-i18n-japanese のメールで聞いてください。書き込みができるようになってその先の質問はこの GitHub issue でやりましょう。enjoy!

**Comment by JunTajima** [comment]
テストです

**Comment by xfq** [comment]
Markdown記法は[GitHub Docs](https://docs.github.com/ja/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)（日本語版）をご参照ください。

**Comment by ghost** [comment]
練習です．

**Comment by tlk714** [comment]
ここに書き込めばいいのかしらね。
GitHubのアカウントはずっと以前に作っていたけれど、久々にログインしたら、パスワード変更を求められた。ウルウル。

**Comment by murata2makoto** [comment]
@KobayashiToshi  @tlk714 

おお、お二人とも出来ているじゃないですか。アットマークを使って人のアカウントを指定すれば、その人に通知が行きます。練習してみましょう。

**Comment by tlk714** [comment]
@murata2makoto @KobayashiToshi 
こう書けば、メールが飛ぶわけね。

**Comment by murata2makoto** [comment]
@tlk714 よく出来ました。パチパチ。では、人の発言を引用してみましょう。行の先頭に>を書くだけです。

> こう書けば、メールが飛ぶわけね。

**Comment by KobayashiToshi** [comment]
メールアドレスを変えるために再度書き込みしました

**Comment by kidayasuo** [comment]
敏先生の登場が待たれますねー

**Comment by himorin** [comment]
引用ですが、該当コメントの
![image](https://user-images.githubusercontent.com/3918572/120425984-2bb3ea80-c3aa-11eb-8ee4-f6545d1aebd0.png)
この赤で丸を付けた３つの点をクリックすると、
![image](https://user-images.githubusercontent.com/3918572/120426059-5140f400-c3aa-11eb-9886-a4e9dee3733d.png)
こういうメニューが出てくる(言語設定によっては日本語で？？)ので、赤丸を付けた２つ目の"Quote reply"を押すと、コメントに追加されます。（コメント入力中であれば一番最後に追加になります。）
また同じメニューから編集とか新規issue立ち上げ、またコメントの位置付きのリンク取得もできますのでご活用ください。

画像を張り付けるときは、コピペが一番楽です。

**Comment by KobayashiToshi** [comment]
> 
> 
> 引用ですが、該当コメントの
> ![image](https://user-images.githubusercontent.com/3918572/120425984-2bb3ea80-c3aa-11eb-8ee4-f6545d1aebd0.png)
> この赤で丸を付けた３つの点をクリックすると、
> ![image](https://user-images.githubusercontent.com/3918572/120426059-5140f400-c3aa-11eb-9886-a4e9dee3733d.png)
> こういうメニューが出てくる(言語設定によっては日本語で？？)ので、赤丸を付けた２つ目の"Quote reply"を押すと、コメントに追加されます。（コメント入力中であれば一番最後に追加になります。）
> また同じメニューから編集とか新規issue立ち上げ、またコメントの位置付きのリンク取得もできますのでご活用ください。
> 
> 画像を張り付けるときは、コピペが一番楽です。

こうすればいいんですね！

**Comment by tlk714** [comment]
で、練習の続き。
東大の矢田勉さんに横書きについての話を頼んだら、岩波新書の「横書き誕生」の著者である屋名池誠さんに繋いでくれるって。
願ったり叶ったり。

**Comment by r12a** [comment]
Would it be useful to translate [Working with GitHub issues](https://www.w3.org/International/i18n-activity/guidelines/issues.html) ?

**Comment by kidayasuo** [comment]
> Would it be useful to translate [Working with GitHub issues](https://www.w3.org/International/i18n-activity/guidelines/issues.html) ?

ah, it is a nice page. Yes, it will be useful.

**Comment by kidayasuo** [comment]
あれ、@tkobayas4 さんが敏先生？？

**Comment by kidayasuo** [comment]
下農さんのメーリングリストへのメッセージ、コピーしておきます。リンク完了。iPhone だと"Connected Accounts" メニューが見えませんね。

> 
> 　並行して、ですが、みなさまのW3Cアカウントにgithubのアカウントを紐づけていただければと思います。
> https://www.w3.org/Systems/db/userInfo
> の自分のW3Cアカウントのページに行って、左のメニューの中の"Connected Accounts"を開き、githubをク
> リックしてアカウント名を入れる、になります。
> 
> 　今のところJL-TFで何か、例えばgithubの権限設定とか、に自動的に利用することは行ってませんが、
> https://www.w3.org/groups/tf/i18n-jlreq/participants
> のような参加者一覧ページに表示されて探しやすくなります。
>

**Comment by himorin** [comment]
> > Would it be useful to translate [Working with GitHub issues](https://www.w3.org/International/i18n-activity/guidelines/issues.html) ?
> 
> ah, it is a nice page. Yes, it will be useful.

should I include this translation into my task list? ;)

**Comment by himorin** [comment]
> 下農さんのメーリングリストへのメッセージ、コピーしておきます。リンク完了。iPhone だと"Connected Accounts" メニューが見えませんね。

たしかに横幅480px以下のデバイスでは表示されない設定になってますね。。スタイルシートの明示的指定なので意図的なのかなぁ、とは思いますが。

**Comment by KobayashiToshi** [comment]
> あれ、@tkobayas4 さんが敏先生？？

龍生さんとまぎらわしいですが，そうです．

最初，使っているメールアドレスで登録しようとしたら，すでに登録されていた．ただし，ユーザー名が不明で，登録できなかった．やむをえず，別のメールアドレスで登録し，書き込んだのですが，後で，ユーザー名が分かったので，前のものは削除し，現行のものにした．

削除すれば，投稿は消えるかと思ったが消えなかった．“ghost”で残ってしまった．申し訳ありません．

**Comment by tlk714** [comment]
ははは、W3Cは、family nameとfirst nameのラテン文字表記から、自動でID名を生成するみたいね。敏さんもぼくも、イニシアルはTKで同じ。
ちなみにぼくのmiddle nameはLawrence。初代教会の助祭ラウレンティウス。Wikiで調べたら、菓子製造人、料理人、栄養士、メイド、宿の管理人、肉屋、ワイン・ビール醸造者、図書館員、兵器製造者、ガラス工、ステンドグラス製造者、コメディアン、学生などの守護聖人でもある、だって。ちょっと笑ってしまった。

**Comment by himorin** [comment]
> ははは、W3Cは、family nameとfirst nameのラテン文字表記から、自動でID名を生成するみたいね。敏さんもぼくも、イニシアルはTKで同じ。

[アカウント設定ページ](https://github.com/settings/profile)からアカウント名にマウスカーソルを載せたときにポップアップする内容を編集したり
![image](https://user-images.githubusercontent.com/3918572/120599162-19a57b00-c482-11eb-877e-55a0f9d5a085.png)
[アカウント名変更](https://github.com/settings/admin)もできたりもしますので、ご検討ください。(すでにコメント中に記述された`@xxx`のようなリンクは更新されないとか[いくつかの影響](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-user-account-settings/changing-your-github-username)もありますが作成直後のアカウントならほぼ影響ないかと)

**Comment by kidayasuo** [comment]
>[アカウント名変更](https://github.com/settings/admin)もできたりもしますので、ご検討ください。(すでにコメント中に記述された@xxxのようなリンクは更新されないとかいくつかの影響もありますが作成直後のアカウントならほぼ影響ないかと)

確かに、自動生成されたもののままでも良いのですが、変えた方がわかりやすいかもしれませんね。私も kidayasuo に変えました。

**Comment by KobayashiToshi** [comment]
>アカウント名変更もできたりもしますので、ご検討ください。

わかりました．以下に変更いたしました．
KobayashiToshi

**Comment by KobayashiToshi** [comment]
>東大の矢田勉さんに横書きについての話を頼んだら、岩波新書の「横書き誕生」の著
>者である屋名池誠さんに繋いでくれるって。
>願ったり叶ったり。

屋名池誠さんの以下の論文はPDFで読むことができます．
“横書きの成立　日本語表記のエポック”（東京女子大学比較文化研究所紀要，
2003年）
https://core.ac.uk/download/pdf/230540776.pdf

**Comment by kidayasuo** [comment]
>屋名池誠さんの以下の論文はPDFで読むことができます．
これはおもしろいですね。

この方の他の研究も面白そうです。タイトルのみで見ることができませんが。
https://k-ris.keio.ac.jp/html/100000229_ja.html

「横書き 日本語」で検索していたら、かつての「いま日本語が危ない」的な書籍も見つけました :) 題して「縦に書け！」
https://www.amazon.co.jp/gp/product/B084FQXH5P

**Comment by ghost** [comment]
May I write a test message here?
--Taro Yamamoto, Adobe

**Comment by KobayashiToshi** [comment]
>屋名池誠さんの以下の論文はPDFで読むことができます．

>これはおもしろいですね。

この論文で，多数参照されている“図書”の連載をまとめたのが，屋名池さんの
“横書き登場　日本語表記の近代”（岩波新書，2003年）です．

**Comment by kidayasuo** [comment]
> この論文で，多数参照されている“図書”の連載をまとめたのが，屋名池さんの “横書き登場　日本語表記の近代”（岩波新書，2003年）です．

なるほど！　いまごろ家に届いているはずなので早く読みたーい。なのに、帰国の7日から3日間囚人生活なんですよ。トホホ…

**Comment by himorin** [comment]
@kidayasuo そろそろこれも閉じますか？

**Comment by kidayasuo** [comment]
yes. I believe it achieved its goal successfully. thanks for the reminder.
