### ISSUE TITLE
Add Japanese issue template?

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#287]
When [filing a new issue](https://github.com/w3c/jlreq/issues/new/choose) in this repo, there is currently only an English version of the template:

<img width="1291" alt="en" src="https://user-images.githubusercontent.com/2863444/125149900-5c87fc00-e16e-11eb-9913-ec3b11ba1a92.png">

which is not friendly to people who do not speak English well. I hope we can add a Japanese version of the template so that more people can send comments. For example:

<img width="1291" alt="ja" src="https://user-images.githubusercontent.com/2863444/125149940-b2f53a80-e16e-11eb-8cb0-15aea39ae527.png">

(The text is just an example, and suggestions for modification are welcome.)

We can achieve this by adding Japanese next to the English text to the existing template files (like https://github.com/w3c/clreq/pull/381/files ) or adding new Japanese-only template files.

**Comment by himorin** [comment]
I have no position on this. @kidayasuo how do you think?

**Comment by kidayasuo** [comment]
Why not. It will make GH issues more accessible. @xfq thank you for your suggestion.
