### ISSUE TITLE
Add mention to close placement of character frames between ruby annotation and its base text

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#319]
add one line.

> なお，親文字の文字の外枠とルビ文字の文字の外枠を接して配置します（3.1の1の図5参照）という説明は，JLReqでは落ちているみたい．図があるかからいいが，何か機会があれば直したい．

**Comment by himorin** [comment]
@KobayashiToshi 確認しましたが、確かに触れられておりません。そして、3.3節のルビ・圏点の項目立ての中で、親文字の両側のどちらに付けるのかや字送り方向でどう合わせるかというのはありますが、ドンピシャはまりそうなところはないような感じを受けました。
で、親文字のどちらに付けるかや字送り方向でどう合わせるかの一つ前、
https://w3c.github.io/jlreq/#choice_of_size_for_ruby_characters
「ルビの文字サイズ」の最後にでも入れる（＆タイトルも微妙に変える？）のはいかがでしょうか？と思うのですが。。
もしよければ日本語文章案をいただけませんでしょうか？

なお、JLreq全体を「外枠」などで洗ってみましたが、ルビや装飾類を外枠に対してどう配置するかという記述はありませんでした。

**Comment by KobayashiToshi** [comment]
***@***.*** 確認しましたが、確かに触れられておりません。そして、3.3節のル
>ビ・圏点の項目立ての中で、親文字の両側のどちらに付けるのかや字送り方向でどう
>合わせるかというのはありますが、ドンピシャはまりそうなところはないような感じ
>を受けました。
>で、親文字のどちらに付けるかや字送り方向でどう合わせるかの一つ前、
>https://w3c.github.io/jlreq/#choice_of_size_for_ruby_characters
>「ルビの文字サイズ」の最後にでも入れる（＆タイトルも微妙に変える？）のはいか
>がでしょうか？と思うのですが。。
>もしよければ日本語文章案をいただけませんでしょうか？
>なお、JLreq全体を「外枠」などで洗ってみましたが、ルビや装飾類を外枠に対してど
>う配置するかという記述はありませんでした。

それでは，“3.3.4 親文字のどちら側にルビを付けるか”の図117の後ろ（以下の前）に見出しを付けないで，以下を追記．

>以下では，ルビの文字サイズを親文字の文字サイズの1/2とし，

なお，ルビの行送り方向の配置位置は，親文字の文字の外枠とルビ文字の外枠を接して配置する（図114参照）．

以下は注記

行送り方向のルビの配置位置　行送り方向のルビの配置位置は，親文字の文字の外枠とルビ文字の文字の外枠を接して配置するのが原則である．しかし，視覚障碍者にとって，親文字とルビの行送り方向の間隔がある程度は空いているのが望ましい場合もあり，この間隔は変更できることが望ましい．
