### ISSUE TITLE
misprints in figures in section 4

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#32]
from https://lists.w3.org/Archives/Public/public-jlreq-admin/2019AprJun/0017.html

figures 4.7 (191) https://w3c.github.io/jlreq/#fig_ad1_16, 4.51 (235), 4.52 (236) have misprints in their texts. Figures of both English and Japanese version need to be fixed. 
Note, figure numbers in brackets are in the current ED version.

**Comment by r12a** [comment]
@himorin could you please add links to the document for the 2nd and 3rd figures mentioned above, like i did for the 1st?  Could you also check that other issues link to the document too, please. (I already changed a few more recent issues for you.)

It's not clear to me what the figures in brackets refer to.

**Comment by himorin** [comment]
sorry that I've copied figure numbers from email in old format, and put current ones into brackets (as in note).
I'll add links and file names, also for other issues.

**Comment by himorin** [comment]
- figure 4.7 (191) : [img3_1_7.png](https://w3c.github.io/jlreq/#fig3_1_7)
- figure 4.51 (235) : [img3_2_2.png](https://w3c.github.io/jlreq/#fig3_2_2)
- figure 4.52 (236) : [img3_2_3.png](https://w3c.github.io/jlreq/#fig3_2_3)

**Comment by himorin** [comment]
Toshi Kobayashi san fixed these three images. Will add as PR.

**Comment by himorin** [comment]
Closing this, PR merged: agreed to merge on last F2F, and checked.
