### ISSUE TITLE
G. Terminologyで、“single line alignment method” の読みが「かたばしらほうしき」になっている

### ISSUE THREAD

**Issue by ogwata** [w3c/jlreq#328]
G. Terminology 用語集 https://www.w3.org/TR/jlreq/#terminology のうち、“single line alignment method” の「よみ」が「かたばしらほうしき」になっています（ローマ字は “soroe”）。次行の “single running head method” と混同したものと思われます。

初めてIssue登録しましたが、なにか間違いがあればご指摘ください。

**Comment by KobayashiToshi** [comment]
>G. Terminology 用語集 https://www.w3.org/TR/jlreq/#terminology のうち、“
>single line alignment method” の「よみ」が「かたばしらほうしき」になっていま
>す（ローマ字は “soroe”）。次行の “single running head method” と混同した
>ものと思われます。

ご指摘のとおり誤りです．以下のように直す．
　かたばしらほうしき　→　そろえ
