### ISSUE TITLE
G. Terminology 用語集「字幅」の和文

### ISSUE THREAD

**Issue by ryukeikun** [w3c/jlreq#334]
G. Terminology [用語集](https://www.w3.org/TR/jlreq/#terminology)のうち、「字幅」の和文は変ですね（英文は大丈夫のようですが）。

> 字幅が，全角の2分の1である文字の外枠．（JIS X 4051）

実際JIS X 4051:2004を確認したところ、下記のように記載となっています。

>3. 定義
>60)　字幅（じはば）文字を配列する方向の外枠の寸法
>参考：字幅は，横書きでは文字の幅となるが，縦書きでは文字の高さとなる

**Comment by KobayashiToshi** [comment]
>G. Terminology 用語集のうち、「字幅」の和文は変ですね（英文は大丈夫のようです
>が）。
>
>字幅が，全角の2分の1である文字の外枠．（JIS X 4051）
>実際JIS X 4051:2004を確認したところ、下記のように記載となっています。
> 
> 3.定義
>60)　字幅（じはば）文字を配列する方向の外枠の寸法
>参考：字幅は，横書きでは文字の幅となるが，縦書きでは文字の高さとなる

はい，あやまりです．現在のものは半角の定義です．旧版では以下です．2020年版のデータ作業中に誤ったものと思われます．

文字を配列する方向（字詰め方向）の文字の外枠の大きさ．一般に字幅の絶対値を文字サイズで除した値で示す．全角，半角，四分角など．字幅は，横組では文字の幅となるが，縦組では文字の高さとなる．

これだと，“generally indicated as a ratio of the size of a full-width character”という英文と意味は同じだが，説明がやや異なる．

**Comment by xfq** [comment]
Proposed PR in https://github.com/w3c/jlreq/pull/330/files
