### ISSUE TITLE
build JL-TF charter for next period from 2023/Jan/01

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#344]
Our [current running charter](https://www.w3.org/International/jlreq/charter/) ends by 2022/Dec/31, and we have significant updates on our working area, such as jlreq-d. So, we need to update it and recharter.

Possible additions and modifications

- add [jlreq-d](https://github.com/w3c/jlreq-d)
- mark as jlreq just for errata, and moving a11y improvements into jlreq-d
- add ruby-t2s-reqs -> @murata2makoto ?
- merge teleconference and video conference in usual meeting schedule? (right above section 1)
- update section numbers of the Process Document?
- add a line of license applicable for deliverables?

**Comment by kidayasuo** [comment]
Thank you @himorin for the heads up. All proposals sound good. I will send the note to the list to solicit feedback.

> • mark as jlreq just for errata, and moving a11y improvements into jlreq-d

How do we add the mark? I would appreciate it if you could do the mass move of a11y issues.

There might be other gh issues that should be moved over to jlreq-d. I can't spend much time rght now until spring but let's plan reviewing all remaining issues in jlreq.

> • add a line of license applicable for deliverables?

Could you do this change?

thanks.

**Comment by himorin** [comment]
> > • mark as jlreq just for errata, and moving a11y improvements into jlreq-d
> 
> How do we add the mark? I would appreciate it if you could do the mass move of a11y issues.

ah, it's for charter, so just stating that was what in my mind.

> There might be other gh issues that should be moved over to jlreq-d. I can't spend much time rght now until spring but let's plan reviewing all remaining issues in jlreq.

Yes, and also we can transfer issues from here to jlreq-d repository.
Let me take some time to develop 'future' related issues.

> > • add a line of license applicable for deliverables?
> 
> Could you do this change?

will raise a PR covering all points shortly.
