### ISSUE TITLE
2.3.1 Hard to understand translation

### ISSUE THREAD

**Issue by bluesunTL** [w3c/jlreq#347]
In section 2.3.1, there is [a note]( https://www.w3.org/TR/jlreq/#n15 ) with translation issues, making it hard to understand.

"There is little market data comparing the number of pages with vertical writing mode and horizontal writing mode, but it is said that both are almost the same."
"縦組と横組の組版されたページ数を調査したデータはほとんどないが，日本における縦組と横組の本の刊行点数は，ほぼ同じくらいと予想される．"

-----

- From "the number of pages with ~ writing mode", it is possible to interpret it as saying that the length of a book (number of pages required) will not be significantly affected if it is written vertically or horizontally. However, there is not enough market data to confirm this.
Considering the Japanese text, this does not appear to be the intent of the note.

- The clause "日本における縦組と横組の本の刊行点数は" is missing in the translation.

For these two reasons, the English translation is unclear, and incomplete compared to the corresponding Japanese text.

Adding a verb after "the number of pages" such as 'composed' or 'typeset' could possibly help clear away the unintended interpretation.

A potential translation accounting for both of these issues could be as follows:
'There is little market data comparing the number of pages composed with vertical writing mode and horizontal writing mode, but there are said to be an almost equal number of books published for the Japanese market using each mode.'

**Comment by himorin** [comment]
@KobayashiToshi ここの「日本における縦組と横組の本の刊行点数は，ほぼ同じくらい」というのは文章の流れからすると、ページ数で比較した場合の本の刊行点数なのかな、とも取れなくはないですが、ページ数とするか本の刊行点数とするか、どちらを意図されてました？（さすがに実販売の冊数での比較は入らないと思います、、、が？）
正直なところは、いい加減な感覚比較なんだからどっちでもいい、という話ではないかとも思うところではありますけれど。

**Comment by murata2makoto** [comment]
この件は、JDCの技術委員会でも議論したことがあります。国会図書館の人も大日本印刷の人もいましたが、誰も分かりませんでした。

追記: 雑誌なんて、縦と横の両方が入り混じってますよね。

**Comment by KobayashiToshi** [comment]
縦組と横組の点数ですが，私の個人的な読書記録に縦組と横組の記録もしていますが，昨年で見ると，合計553点のうちで横組は60点です．私の読書傾向（文系）をある意味で示しており，縦組が圧倒的に多いのですが，それなりに横組もある．

**Comment by KobayashiToshi** [comment]
>@KobayashiToshi ここの「日本における縦組と横組の本の刊行点数は，ほぼ同じくら
>い」というのは文章の流れからすると、ページ数で比較した場合の本の刊行点数なの
>かな、とも取れなくはないですが、ページ数とするか本の刊行点数とするか、どちら
>を意図されてました？（さすがに実販売の冊数での比較は入らないと思います、、、
>が？）

発行部数で考えると，ベストセラーは圧倒的に縦組なので，ページ数または刊行点数ということだと思います．ただし，ページ数または刊行点数とでは，あまり差はないと思われるが，

高島義雄著“印刷ハンドブック―活版整版技術編―”（東京都印刷工業組合，1967年）によれば，日本で刊行されている点数の50％は横組であるといわれており，組版のページ数では横組が60％を超えるものと推定されるとしている．

との説明があるので，点数よりはページ数で考えると，横組はやや増えるということも考えられる（縦組より横組の方がページ数の多い本が多い）．

もし，記述をはっきりさせるなら，とりあえず刊行点数でいいでしょう．

**Comment by himorin** [comment]
> 発行部数で考えると，ベストセラーは圧倒的に縦組なので，ページ数または刊行点数ということだと思います．ただし，ページ数または刊行点数とでは，あまり差はないと思われるが，
> もし，記述をはっきりさせるなら，とりあえず刊行点数でいいでしょう．

いろいろとありがとうございます。
これの次のノートでは、横組が増えていくと予想されるが新聞や小説は縦組なので、縦組の重要性は当面は変わらないであろう、という流れではありますので

- いっそページ数とか刊行点数とかを言わずに「出版物において縦組と横組の数（ページ数や刊行点数）の比較を調査したデータはほとんどないが，日本においてはほぼ同じくらいと予想される．」位に完全にぼやかしてしまう
- はっきり言い切る方向で「縦組と横組の組版された刊行点数を調査したデータはほとんどないが，日本における縦組と横組の本の刊行点数は，ほぼ同じくらいと予想される．」と全部刊行点数にそろえる

のどちらでもいいのかな、とは思ったりしました。みなさまどちらがお好みでしょう？（どうせNote:の部分ですし・・・）

**Comment by murata2makoto** [comment]
My two cents.

完全にぼやかした前者。

**Comment by himorin** [comment]
> My two cents.
> 完全にぼやかした前者。

敏先生 (@KobayashiToshi )、いかがでしょう？

**Comment by KobayashiToshi** [comment]
>完全にぼやかした前者。

そうしましょう．

**Comment by himorin** [comment]
では、以下のように日英共に更新します。
After discussion within JLreq TF, we have decided to modify both Japanese and English text, since this text is for stating that both vertical and horizontal writing mode are important and used for Japanese printed publishing, and also there is no clear survey result on neither total pages of published books, total number of copies of published books, nor number of published books.

> 出版物において縦組と横組の数（ページ数や刊行点数）の比較を調査したデータはほとんどないが，日本においてはほぼ同じくらいと予想される．
>There is little market data comparing numbers (e.g. total pages of published books, total number of copies of published books) between vertical writing mode and horizontal writing mode, but it is said that both are almost the same.
