### ISSUE TITLE
3.1.10 "¢" listed as prefix

### ISSUE THREAD

**Issue by bluesunTL** [w3c/jlreq#350]
In [section 3.1.10d]( https://www.w3.org/TR/jlreq/#unbreakable_character_sequences ), the English translation lists the cent sign "¢" is listed as a prefix instead of a postfix.

"Between prefixed abbreviations (cl-12) (YEN SIGN "¥"，DOLLAR SIGN "$"，CENT SIGN "¢" etc.) and the following arabic or ideographic numeral (see Figure 82). The reason is that such character sequences are to be handled as one unit."
"前置省略記号（cl-12）（円記号[¥] (YEN SIGN)，ドル記号[$] (DOLLAR SIGN)など）とその後ろにくるアラビア数字・漢数字との間（Figure 82）．それらの文字列を一体として扱いたいためである．"

-----

In other parts of the document, the cent sign is considered a postfix, and being a postfix matches with its general English usage, so the English translation appears to be in error.

A potential version equivalent to the Japanese text could be as follows:
"Between prefixed abbreviations (cl-12) (YEN SIGN "¥"，DOLLAR SIGN "$" etc.) and the following arabic or ideographic numeral (see Figure 82). The reason is that such character sequences are to be handled as one unit."

**Comment by himorin** [comment]
@KobayashiToshi @tlk714 @kidayasuo 前置省略記号($100)とかにセントも混じってる（英語版だけ）は、いわゆる日本語（縦組み？？）の中では昔はすべからく金額単位記号は前置されていた、というところからきているのだと思うのですが、その理解で正しく、これは特に修正不要、でいいですよね？
なんか、どちらかというと、前置省略・後置省略でなく、数字と省略記号の文字クラス間での分割禁止とすべきなんだろうかなぁ@jlreq-d、という感じもするところです・・・。

**Comment by KobayashiToshi** [comment]
>***@***.***、という感じもするところです・・・。

￠(U+0A2,CENT SIGN)は，日本語版，英語版ともに“後置省略記号”です（慣習ということで）．分割については， 前置も後置も同じ扱いともいえるので，同一文字クラスにできる．ただ，問題としたい分割や字間の処理が前置と後置では前と後ろと異なるので，どうでしょうか．

**Comment by himorin** [comment]
@KobayashiToshi  コメントありがとうございます。すみません、確かに文字クラスの表を見たらU+00A2は後置でした。本文修正します。
jlreq-d的な文字クラスの方、2つの文字クラスが並んだ際のその間、という記述をしていることを考えると、前後の並び順がどちらかは気にしなくてもいいのかなと思っていました、が、もう少し考えてみます。。あと、unicodeの属性ではどうなっているかも確認します。
