### ISSUE TITLE
Fig. 29 Nonsense translation

### ISSUE THREAD

**Issue by bluesunTL** [w3c/jlreq#352]
In section 2.3.2d1, [Figure 29]( https://www.w3.org/TR/jlreq/#fig1_24 ), the English translation is nonsense.

"example arrange without completing it with the upper column"
"example that it arrange only in the upper column"
"なりゆきで下段まで配置した例"
"上段だけ配置した例"

-----

"Arrange" is unconjugated, and overall the sentences are hard to understand.

A potential translation with consideration to context could be as follows:
'example when lines have reached the lower column'
'example when lines are only placed in the upper column'

**Comment by himorin** [comment]
Considering important point of "nariyuki", I would update as:

> right: example where lines are only placed in the upper column
> left: example where lines are placed in both upper and lower column without uniform number
