### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#359]
https://w3c.github.io/jlreq/#composition_of_japanese_and_western_mixed_texts

> There are a lot of examples of Japanese text in which Western and/or Greek letters are mixed among Japanese letters.

"Western and/or Greek letters" should probably be "Latin and/or Greek letters". We found this during a CLReq [meeting](https://www.w3.org/2023/02/21-clreq-minutes.html#t08).

**Comment by himorin** [comment]
Looking around text with "Western" within whole text, and considering founding like:

- [Japanese and Western mixed text composition](https://w3c.github.io/jlreq/#term.japanese-and-western-mixed-text-composition) is described as `To mix Japanese text and Western text in the same composition.`
- character class cl-27 is named as `Western characters`, which includes several others than Latin and Greek characters
- Words `Letter` and `Character` are often in mixed use, like [Jizura](https://w3c.github.io/jlreq/#term.letter-face) is written as `Letter face` as terminology.

it is not fixed easily just by replacing `Western` with `Latin`, which is also not correct per traditional(?) Japanese writings.

So, how about as PR https://github.com/w3c/jlreq/pull/366 ?
