### ISSUE TITLE
プロポーショナルな欧字＋始め括弧類の間のアキについて

### ISSUE THREAD

**Issue by CHRIBUR0309** [w3c/jlreq#376]
[W3C Editor's Draft 24 July 2023](https://w3c.github.io/jlreq)を参照しています。

[3.2節](https://w3c.github.io/jlreq/#japanese_and_western_mixed_text_composition)について、プロポーショナルな欧字＋始め括弧類の間のアキの標準的な設定が見当たらなく思われます。具体的には

```Text
Python（パイソン）とは、
```

で、nと（の間のアキが分かりません。二分アキでしょうか？

**Comment by KobayashiToshi** [comment]
>W3C Editor's Draft 24 July 2023を参照しています。
>3.2節について、プロポーショナルな欧字＋始め括弧類の間のアキの標準的な設定が見
>当たらなく思われます。

JLReqの“B. Spacing between Characters 文字間の空き量”にある“表1 文字間の空き量（PDF版）”の欧文用文字（cl-27）と始め括弧類（cl-1）を見てください．それによれば，cl-01）と欧文用文字（cl-27）の字間は，二分アキです．
