### ISSUE TITLE
Wrong Japanese section title §3.3.2

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/jlreq#38]
"3.3.2 Choice of Base Characters to be Annotated by Ruby ルビをどのような言葉に，どのように付けるかは各種の方法がある．"
https://w3c.github.io/jlreq/#choice-of-base-characters-to-be-annotated-by-ruby

https://github.com/w3c/jlreq/blob/314dd6a60d45b82b2ec400172524750da6451123/index.html#L3582-L3585

It seems a bug on English-Japanese merging. The original Japanese section title for §3.3.2 was "ルビの付け方".

**Comment by r12a** [comment]
Thanks for spotting this @MurakamiShinyu.  Since it's a merge bug, i fixed it with a direct commit.
