### ISSUE TITLE
Japanese Script Resources page

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#438]
I'm hoping to publish a new FPWD called Japanese Script Resources, in line with all other scripts currently being worked on in our Language Enablement program.  See a [list of documents](https://github.com/w3c/i18n-activity/wiki/LReq-documents). I wanted to bring your attention to this page in case you have any questions or comments.  I hope to publish it on 23 July.

Going forward, all documents with a short name ending in -lreq (with an actual hyphen in the short name) will be focused on a script, rather than a specific language. These -lreq docs point to requirements and script descriptions, tests, GitHub discussions, type samples, and more, organised by topic.  The proposed Japanese page will, of course, point to jlreq, jlreq-d, simple-ruby, and any other relevant documents produced by the jlreq group, and can be viewed at:

https://w3c.github.io/jlreq/jpan/

The page is particularly useful for gap analysis work (bringing together many of the resources needed to create a gap report), and will be regularly updated as new resources become available.  (Updates to discussions, tests, and type samples are updated automatically.)

In addition, these -lreq documents have a set of headings that are standardised across all other -lreq docs, as well as -gap documents, the Language Matrix, the Language Enablement Index, and the various GH issue labels in the many repos.  That document structure has been applied to the Arabic, the Tibetan, and Mongolian layout requirements docs already. I plan to apply it also to the Korean and Ethiopic layout requirements docs, and at the request of the folks in the clreq group i'm working on restructuring the Chinese Layout Requirements along similar lines.  It may be worth considering whether the new jlreq-d document would also benefit from adopting this structure, too.

Please let me know if you have any comments or questions. Thanks.

**Comment by kidayasuo** [comment]
Thank you for putting this together.

What is the distinction between jlreq/jlreq-d, j-lreq, [Japanese Script Resources page](https://w3c.github.io/jlreq/jpan/), and [your document](https://r12a.github.io/scripts/jpan/ja)? I am a bit confused.

I agree that having some common structure between documents for different scripts is beneficial. At the same time, there might be cases where a one-size-fits-all structure does not work well and requires adjustments. I am happy to work with you to explore a better common structure.

Is the proposed common structure described somewhere, or is it best to look at examples such as a-lreq?

**Comment by r12a** [comment]
> What is the distinction between jlreq/jlreq-d, j-lreq, [Japanese Script Resources page](https://w3c.github.io/jlreq/jpan/), and [your document](https://r12a.github.io/scripts/jpan/ja)? I am a bit confused.

[Japanese Script Resources page](https://w3c.github.io/jlreq/jpan/) (which will have the short name jpan-lreq, although the short names are not particularly important) provides people creating gap reports and provides implementers with a way to find resources such as GH discussions, tests, type samples, etc related to a particular topic.  The structure of the document is consistent across script resource docs for all scripts, and all relevant repositories use labels that conform to that structure).

In addition, the Japanese Script Resources page points to useful sources of information about how a script works, requirements, etc.  

If the [existing JLReq](https://www.w3.org/TR/jlreq/) contains any such information for a given topic, it is linked to first.

As other documents are published by the jlreq group, they will also be pointed to.  This will include jlreq-d, when there is something to point to.

I usually only add a pointer to [my orthography notes document](https://r12a.github.io/scripts/jpan/ja) if i think it contains some information that might be useful but that is not included in jlreq.


> I agree that having some common structure between documents for different scripts is beneficial. At the same time, there might be cases where a one-size-fits-all structure does not work well and requires adjustments. I am happy to work with you to explore a better common structure.

The structure of the _Script Resources pages_ will need to be the same as they are currently, since there is a strong link between the structure of various items, including the Script Resources document, the gap analysis document, the Language Matrix, the (work in progress) Language Enablement Index, and the labels for language enablement spread through many repositories.  We have tooling that relies on these mappings to make it easier to maintain and build cross-references into the pages.

However, it's not essential that pages linked to under the Requirements heading (ie. JLReq and JLReq-D) have the same structure.  I don't think we'd want to change the structure of the existing JLReq, but i thought it might be worth considering using the standard structure for JLReq-D, since it helps people find things, and also it tends to show up gaps in coverage. (It also makes it easier to link to requirements, since it tends to keep related information together so that a single link will often suffice; and keeping related information from spreading around the document also makes it easier to find information when reading that document.)

Wrt one-size-fits-all, if we were indeed to use this structure for JLReq-D we could make some tweaks if needed, since the requirements documents don't need to follow the rigid structure of the other documents mentioned earlier. However, you may have spotted that the structure is the same as that which i use for parts of my own orthography notes.  I have been developing and refining this classification to describe many, very varied orthographies (currently 89 - see https://r12a.github.io/scripts/index.html#scriptnotes), and have done so over many years now, and it works quite well. (Which is why Fuqiao and i decided to use it for the W3C materials too.)

> Is the proposed common structure described somewhere, or is it best to look at examples such as a-lreq?

There's a template i use to create new Script Resources docs at https://w3c.github.io/i18n-activity/templates/lreq_doc/lreq_template.html    It has the full set of headings (some of which are dropped if not relevant, eg. Cursive Text), and it has short italicised paragraphs beneath each heading that give an idea of what's included in each section.  That gives an idea of what the basic skeleton might be.

The organisation of material within those headings is whatever works best for the language in question.  

Btw, fwiw, one area that i find can often be improved by a clearer separation of ideas is that of text alignment/justification vs. text spacing. If you're interested, you can see how i broke out ideas related to text spacing (as opposed to justification) in my orthography notes at https://r12a.github.io/scripts/jpan/ja.html#letterspace. 

Does that help?

**Comment by kidayasuo** [comment]
Thank you so much for the clarification. It helped a lot, and I believe I now have a clearer understanding. Let me verify if my understanding is accurate: The Script Resources (aka xx-lreq) page is a centralized collection of references for all information regarding a specific script, and it follows a unified structure. I agree that having a unified structure is beneficial. The Script Resources page points to other related documents such as jlreq, jlreq-d etc.

Regarding your suggestion to use the standard structure for JLReq-d, while I do not know at this point if the structure works for the particular document, I do see the benefit of having landing points for links from the Script Resources page. Let us discuss this further at JLReq TF's next meeting on 8/13. Thank you for the template—it greatly helps clarify what should be discussed under each section.

Thank you as well for the idea of separating alignment/justification from spacing. I will read and respond. Your orthography notes have provided me with fresh insights from the perspective of someone whose main language is not Japanese, which is very beneficial.

**Comment by r12a** [comment]
@kidayasuo thanks for the reply.

> Let me verify if my understanding is accurate:

Yes, indeed.

Just to reiterate: there is no absolute need to adopt the same structure for the JLReq-D document (we can still link to the relevant section(s) – which is one reason we keep the Script Resources document separate from the Layout Requirements docs), but keeping the same structure has its conveniences (such as easier linking, and showing up topics that might have been missed).  The internal content and structure of each section would, of course, be very much language specific.

**Comment by kidayasuo** [comment]
All right. Are there anything else you want the task force to do other than to discuss how we support the link targets, and possibly adopt the section structure in jlreq-d?

By the way, the shorthand name -lreq was the source of my confusion, and I still find it a bit unclear. The abbreviation (language line layout requirements?) doesn’t relate to the spelling of “Script Resources” and is almost identical to the shorthand name of xxlreq documents. Could it be changed to something closer to “Script Resource”? or actually as it is not that long can it always be fully spelled?

**Comment by r12a** [comment]
> Are there anything else you want the task force to do other than to discuss how we support the link targets, and possibly adopt the section structure in jlreq-d?

No, i think that's it.  (Btw, the Japanese Script Resources page is now scheduled for publication next Tuesday.)

Wrt short names, I would also have also preferred something slightly different, but my hand was constrained due to previous publications, and we can't now change them.  At least, they are all consistent. But as i mentioned before, the short name should just be regarded as an arbitrary label – it's safest to generally refer to documents using their title.  Although i think 'JLReq' will probably stick for the Japanese Layout Requirements, and we should refer to jpan-lreq as the 'Script Resources' doc rather than by short name.

**Comment by xfq** [comment]
Regarding the location of editor's draft, I feel that `resources/` is easier to remember than `jpan/` (https://w3c.github.io/jlreq/jpan/). Can we consider using `resources/` (like [clreq](https://www.w3.org/International/clreq/resources/) does)?

**Comment by kidayasuo** [comment]
> Can we consider using `resources/` (like [clreq](https://www.w3.org/International/clreq/resources/) does)?

I am fine with that. The "resources/" looks reasonable. thanks.

**Comment by kidayasuo** [comment]
Hi Richard (@r12a), the task force discussed this at the meeting on 8/13. It was concluded that it would be appropriate for jlreq-d to consider creating links targets from the relevant sections of the Script Resources page. For details see below.

[meeting notes](https://github.com/w3c/jlreq/discussions/441)
[discussion for each section of the resource page](https://github.com/w3c/jlreq-d/discussions/62#discussioncomment-10332328)

**Comment by r12a** [comment]
Noted. Thanks.
