### ISSUE TITLE
Comment on Japanese Script Resources

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#439]
https://www.w3.org/TR/2024/DNOTE-jpan-lreq-20240730/#h_script_overview

> See the table to the right for a brief overview of features for the modern Japanese orthography. The character count reflects a typical set of characters needed for everyday reading and writing: there are thousands more kanji characters that could be added for other purposes.

There doesn't seem to be a table on the right?

**Comment by r12a** [comment]
Done.

**Comment by xfq** [comment]
Thank you! Closing.
