### ISSUE TITLE
Custom-defined counter styles have confusing support information

### ISSUE THREAD

**Issue by Psychpsyo** [w3c/jlreq#444]
The document at https://www.w3.org/TR/jpan-gap/ says: "Gecko and Blink based browsers now both support custom-defined counter styles. Webkit and Blink browsers do not."
This seems to imply that Blink both does and does not support this with no information on what that means. (I assume this is a typo)

Screenshot:
![image](https://github.com/user-attachments/assets/042db1ec-3ca7-4f04-b48a-fe4654f60137)

**Comment by r12a** [comment]
Thanks for the comment!   This actually led to a lot of work around this topic.  The gap report has now been rewritten (see https://www.w3.org/TR/jpan-gap/#issue170_writing_mode), and hopefully this issue is resolved, so i'll close it.

If there is an outstanding problem, feel free to reopen.
