### ISSUE TITLE
Fig. 3.63 nakatsuki-ruby and katatsuki-ruby

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/jlreq#5]
The top labels of Fig. 3.63 are wrong: nakatsuki-ruby and nakatsuki-ruby. This should be nakatsuki-ruby and katatsuki-ruby.

**Comment by tripu** [comment]
I can't find a &ldquo;fig. 3.63&rdquo; on [`w3c.github.io/jlreq`](https://w3c.github.io/jlreq/), @MurakamiShinyu.

Do you mean [`images/img2_3_14.png`](https://github.com/w3c/jlreq/blob/gh-pages/images/img2_3_14.png), that is used in [*§ 3.3.5 Positioning of Mono-ruby with Respect to Base Characters*](https://w3c.github.io/jlreq/#fig2_3_14-en)?

**Comment by MurakamiShinyu** [comment]
Yes, I mean [images/img2_3_14.png](https://github.com/w3c/jlreq/blob/gh-pages/images/img2_3_14.png), that was [Fig. 3.63](https://www.w3.org/TR/jlreq/#fig2_3_14-en) on the published version.

**Comment by tripu** [comment]
(Ah, I was confused because fig. 3.63's anchor is `#fig2_3_14-en`. Thank you for clarifying!)

**Comment by himorin** [comment]
Figure 3.63, img2_3_14.png : Figure 119 https://w3c.github.io/jlreq/#fig2_3_14

**Comment by himorin** [comment]
Toshi Kobayashi san will fix figure in English version. 
text and Japanese version is correct.

**Comment by himorin** [comment]
Closing this, PR merged: agreed to merge on last F2F, and checked.
