### ISSUE TITLE
[Editorial] wrong lines introduced by combining (and moving to respec) process

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#52]
not all could be editorial, but putting all here to list ones introduced by combining (and moving to respec?) process at 2019/May. (sorry that this is not from detailed comparison, but just skim through...)
Note: have not checked link targets; not including inconsistent applied links to terms references; WIP - for sections 1-3 as for now

- Editors: 'Hiroyuki Chiba' is in both 1st and 2nd for before, marked as 2nd for after
- Editors: 'Tatsuo Kobayashi' is as 'JustSystems' for 1st and 'Invited Expert' for 2nd for before, in both 1st and 2nd as 'JustSystems' for after
- Editors: 'Felix Sasaki' is as 'University of Applied Sciences Potsdam' for 1st and 'DFKI GmbH' for 2nd for before, in both 1st and 2nd as 'DFKI GmbH' for after (Kanji name 'Felix 佐々木' is ok to be dropped?)
- [section A.28](https://w3c.github.io/jlreq/#warichu-opening-brackets-cl-28-cl-28) title has right angle bracket at the first character of Japanese text 'Warichu opening brackets (cl-28) >割注始め括弧類（cl-28）'
- [section 2.2.4 note 1](https://w3c.github.io/jlreq/#n7), [section 2.2.5(a) note 1](https://w3c.github.io/jlreq/#h-note-10), [section 3.2.5 note 1](https://w3c.github.io/jlreq/#h-note-99) : link in English text does not have section mark
- [section 2.6.3(a)](https://w3c.github.io/jlreq/#id107), [section 3.1.3(a) note 1](https://w3c.github.io/jlreq/#h-note-53), [section 3.1.3(b)](https://w3c.github.io/jlreq/#id152) text (and many more??) : has term reference link with 'termref2nd' not 'termref' (both English and Japanese)
- [section 3.3.5](https://w3c.github.io/jlreq/#positioning-of-mono-ruby-with-respect-to-base-characters) paragraph 2: Japanese text is included into figure part
- [section 3.3.7](https://w3c.github.io/jlreq/#positioning-of-jukugo-ruby-with-respect-to-base-characters) paragraph 2, section 3.3.7 [notes 2](https://w3c.github.io/jlreq/#h-note-122) and [3](https://w3c.github.io/jlreq/#h-note-123), [section 3.4.2 note 2](https://w3c.github.io/jlreq/#h-note-133): a link to appendix in English text are linked with section mark
- [Appendix F.4 paragraph 4](https://w3c.github.io/jlreq/#en-app6_5) does not have its-locale-filter-list attribute

**Comment by r12a** [comment]
Chiba-san's edition information appears to be a problem dating from the port to Github.

It's perhaps worth asking the question: Is it useful to indicate which of the 2 previous versions an editor was involved (?)

We could list both affiliations for Kobayashi-san and Sasaki-san (?), or we could remove affiliations from previous editors.  I suppose it depends whether we want to recognise the organisations that supported the work. (I have no preference.)

**Comment by r12a** [comment]
>  Note: have not checked link targets; not including inconsistent applied links to terms references; WIP - for sections 1-3 as for now

I did check all links before posting.

**Comment by r12a** [comment]
> section A.28 title has right angle bracket at the first character of Japanese text 'Warichu opening brackets (cl-28) >割注始め括弧類（cl-28）'

fixed

> section 2.2.4 note 1, section 2.2.5(a) note 1, section 3.2.5 note 1 : link in English text does not have section mark

Fixed 24 links of this kind.  Hopefully they include the 3 list above.

> section 2.6.3(a), section 3.1.3(a) note 1, section 3.1.3(b) text (and many more??) : has term reference link with 'termref2nd' not 'termref' (both English and Japanese)

There appear to be 242 of these term references, but they also existed in https://www.w3.org/TR/jlreq/, so we need to try to understand whether or not there's a significance in the class name being termref2nd, instead of just termref.

**Comment by r12a** [comment]
> section 3.3.5 paragraph 2: Japanese text is included into figure part

fixed

> section 3.3.7 paragraph 2, section 3.3.7 notes 2 and 3, section 3.4.2 note 2: a link to appendix in English text are linked with section mark

i think these will now be fixed as mentioned above.

**Comment by r12a** [comment]
I reran the link checker, and there was only 1 problem: the link to the Japanese version of the doc in the SOTD at https://w3c.github.io/jlreq/#sotd.  I made that link point to the current doc with ?lang=ja in the URL, and added another link to the English version.  See https://github.com/w3c/jlreq/commit/6cdaac3b7c68d0cc2d22d1ef21fdc9080e39715b

**Comment by himorin** [comment]
(links added to the first comment - or description?)

**Comment by himorin** [comment]
> 
> 
> Chiba-san's edition information appears to be a problem dating from the port to Github.
> 
> It's perhaps worth asking the question: Is it useful to indicate which of the 2 previous versions an editor was involved (?)
> 
> We could list both affiliations for Kobayashi-san and Sasaki-san (?), or we could remove affiliations from previous editors. I suppose it depends whether we want to recognise the organisations that supported the work. (I have no preference.)

Kida-san (@kidayasuo ), let me propose to add this to agenda for our next F2F.

**Comment by himorin** [comment]
gone toward the end of document. 

Added followings to the first comment (or description):
- [Appendix F.4 paragraph 4](https://w3c.github.io/jlreq/#en-app6_5) does not have its-locale-filter-list attribute

Also added issues:
- #53 Inconsistency between English and Japanese version in section 4.4.2 note 1 and 2
- #54 English text for '通用名称' in Appendix A tables
- #55 Some character samples in Appendix A tables are in full-width character
- #56 'Appendix G' is shown as bare text in section 4.1.1 note 7

**Comment by himorin** [comment]
> > section 3.3.7 paragraph 2, section 3.3.7 notes 2 and 3, section 3.4.2 note 2: a link to appendix in English text are linked with section mark
> 
> i think these will now be fixed as mentioned above.

I may misunderstand their behavior before... I saw several links says like 'Appendix B. xxxx' and respec is automatically switch between section mark and 'Appendix' following the target of link, but seems not true.
All appendix seems to be shown as '§ A' format now.

**Comment by himorin** [comment]
closing this issue, all referenced issues closed
