### ISSUE TITLE
Inconsistency between English and Japanese version in section 4.4.2 note 1 and 2

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#53]
link: [note 1](https://w3c.github.io/jlreq/#h-note-260), [note 2](https://w3c.github.io/jlreq/#h-note-261)

Japanese text has links to example as "（Figure 285及びFigure 294）" (note 1) or "（Figure 286）" (note 2), but no such text in English version.

**Comment by r12a** [comment]
fwiw, i remember noticing a few situations like this while doing the merge.  I believe that the discrepancy is in the current TR version too.  (Having the new merged version should help a lot for spotting this kind of thing.)

**Comment by himorin** [comment]
PR #65 merged.
