### ISSUE TITLE
Japanese translation of "Former editors"

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#57]
The Japanese version of "former editors" is currently "編者（第２版）". IMHO it should be "元編者" or something similar.

See also https://github.com/w3c/jlreq/commit/c019201e3b41dccba252a7e7500ae963f18462ce#r33461366

**Comment by r12a** [comment]
I agree.  I had meant to do something about that, but forgot.  @kidayasuo could you suggest a translation for "Former editors"?  Then i'll make the change.

**Comment by r12a** [comment]
@kidayasuo @himorin Can you recommend a translation for "Former editors" ?  Thanks.

**Comment by kidayasuo** [comment]
I can't think of single or compound word (jukugo) for "former editors". How about "以前の版の編者"?  If it is specific to the second revision you can say "第2版の編者".

**Comment by r12a** [comment]
Thanks @kidayasuo.  It's not specific to the 2nd version, so i guess we should use 以前の版の編者.

**Comment by kidayasuo** [comment]
👍
