### ISSUE TITLE
用語集が読みづらいです。

### ISSUE THREAD

**Issue by gtk2k** [w3c/jlreq#6]
日本語での仕様作成ありがとうございます。

[用語集](https://w3c.github.io/jlreq/ja/#term.composition)
ものすごく些細なことで申し訳ございませんが、
用語集のテーブルの「用語」「よみ」の列幅が狭くなっており、読みづらくなっています。
もし、可能でしたら幅の調整を行っていただけたらと思います。
よろしくお願いします。

**Comment by xfq** [comment]
Would add some padding to the table cells (like [clreq](https://w3c.github.io/clreq/#glossary)) help?

**Comment by r12a** [comment]
Yes, i had that in mind. But there is currently an unanswered question about how to merge the glossaries for the two languages to fit the new multilingual format, and i was waiting for resolution of that question before addressing the formatting.  I don't remember seeing a resolution in the minutes of the recent FTF, so perhaps it would be good to change the style in the meantime.

**Comment by xfq** [comment]
Agreed.

Should we file an issue to track the merging of the two glossaries (if there isn't already one)?

**Comment by xfq** [comment]
> Should we file an issue to track the merging of the two glossaries (if there isn't already one)?

I just saw this issue be discussed during a F2F earlier this year: https://lists.w3.org/Archives/Public/public-jlreq-admin/2019AprJun/0122.html

**Comment by r12a** [comment]
For question of merging glossaries, see https://github.com/w3c/jlreq/issues/60.

**Comment by kidayasuo** [comment]
Commented on the pull request.

**Comment by himorin** [comment]
closed by #99
