### ISSUE TITLE
§3.7.4 note 2の記述に誤りがあります

### ISSUE THREAD

**Issue by yuw** [w3c/jlreq#72]
§3.7.4 note 2の記述中，次の誤りがありました．
誤：and GREEK CAPITAL LETTER SIGMA "Σ"
正：and N-ARY SUMMATION "∑"

対応する和文部分も次のようになると思われます．
誤：直和記号（シグマ）なども
正：総和記号なども

**Comment by himorin** [comment]
https://w3c.github.io/jlreq/#h-note-152

for symbol used there is http://unicode.org/cldr/utility/character.jsp?a=03A3 and 'GREEK CAPITAL LETTER SIGMA', but it shall refer https://unicode.org/cldr/utility/character.jsp?a=2211 'N-ARY SUMMATION' as pointed.

@kidayasuo is this a correct change?

**Comment by kidayasuo** [comment]
I do not think this is an error. The JLReq version 2 is based on JIS X0208 / X0213 (confirmed with bin-sensei, the author of JLReq) and not Unicode. The character in question is 1-06-18 in JIS, and it corresponds to U+03A3 which is GREEK CAPITAL LETTER SIGMA. However I agree the future JLReq should based on Unicode, the version 2 is not.

I recommend closing this issue as behaving correctly.

**Comment by kidayasuo** [comment]
ah, I noticed on the other hand the term in the original Japanese clearly has an error as pointed out in the report. The 直和記号 is not a シグマ. It should be "総和記号（シグマ）".
