### ISSUE TITLE
remove unrequired U+200B-s

### ISSUE THREAD

**Issue by himorin** [w3c/jlreq#78]
sample from line 2246, this line has U+200B as below.
> 始め括弧類，終わり括弧類，読点類，句点類及び<200b>中点類が<200b>連続する<200b>場合の<200b>配置方法

are these really required for document? or just inserted by accident?
@kidayasuo do you have any information on their history?

**Comment by r12a** [comment]
[@himorin please use links to point to items, rather than line numbers (which are not reliable over time).]

Although it's not done consistently throughout the document, I suspect that those zero-width spaces may have been inserted in order to improve the line-breaking for the heading text.

**Comment by himorin** [comment]
sorry not adding pointer. this line is Japanese version of section title of
https://w3c.github.io/jlreq/#positioning_of_consecutive_opening_brackets_closing_brackets_comma_full_stops_and_middle_dots

**Comment by himorin** [comment]
decided to close this without fix, during Dec 13 2019 F2F meeting.
