### ISSUE TITLE
3.3.8 second paragraph: Fix English for inter-character spacing of ruby

### ISSUE THREAD

**Issue by macnmm** [w3c/jlreq#80]
Text says: 

> The following are the general rules (see Figure 135 and Figure 136). They were established especially in order to avoid misreading and to maintain the beauty of the layout. Noted that the detailed value of spaces between characters for cases of ruby letters hanging over the base characters is described in § B. Spacing between Characters 文字間の空き量 as Table 1 in accordance with § 3.9 About Character Classes 文字クラスについて .

the "spaces between characters" phrase is actually talking about "inter-character spacing".

**Comment by himorin** [comment]
3.3.8: https://w3c.github.io/jlreq/#adjustments-of-ruby-with-length-longer-than-that-of-the-base-characters
text is a second sentence of a second paragraph.
