### ISSUE TITLE
Note below Fig 136: English version is hard to understand

### ISSUE THREAD

**Issue by macnmm** [w3c/jlreq#84]
> Because ruby letter may go over the base characters and overhang to adjacent hiragana (cl-15) etc. up to the full-width size of a ruby letter, ruby letters from before and from after a base hiragana (cl-15) may be consecutive without space like Figure 137. Such cases are not recommended because of the possibility of misreading. It is recommended to insert one em space between former ruby letters and latter ruby letters. There are two ways to carry out this. One is to reduce the maximum size of overhang to the hiragana (cl-15) base character of before ruby letter and after ruby letter, and the other is to reduce the maximum size of overhang to the hiragana (cl-15) base character of after ruby letter. The latter case is carried over to differently set the limit of overhang from before and from after. Firstly, set the ruby letters from before as usual, i.e. ruby letter may overhang up to the full-width size of a ruby letter. Secondly, ruby letter from after shall be set with one em space before, namely, the ruby letter from after can not go over the base hiragana (cl-15) letter in between. Hence, appropriate size space shall be inserted between base characters themselves (see Figure 138).

This paragraph could use some editing. I volunteer...

**Comment by himorin** [comment]
link: https://w3c.github.io/jlreq/#h-note-124
